load("//:rules.bzl", "runai_cc_auto_library")

runai_cc_auto_library(
    name = "reader",
    deps = [
         "//common/range",
         "//common/response",
         "//common/s3_wrapper",
    ],
)
