# Config setting for Azurite testing support
# Use with: bazel build --config=azurite //azure:libstreamerazure.so
config_setting(
    name = "azurite_testing",
    define_values = {
        "azurite_testing": "true",
    },
    visibility = ["//visibility:public"],
)