load("//toolchain:configure.bzl", "configure_toolchain")
configure_toolchain(name = "toolchain")
load("//toolchain:deps.bzl", "load_toolchain_deps")
load_toolchain_deps()

new_local_repository(
    name = "aws",
    path = "/opt",
    build_file = "//third_party:aws.BUILD"
)

load("//:rules.bzl", "runai_cc_test_dependencies")
runai_cc_test_dependencies()
