load("//:rules.bzl", "runai_cc_auto_library")

runai_cc_auto_library(
    name = "obj_store_credentials",
    deps = [
        "//common/backend_api/object_storage",
        "//utils/logging",
    ],
)
