load("//:rules.bzl", "runai_cc_auto_library")

runai_cc_auto_library(
    name = "file",
    deps = [
        "//common/exception",
        "//streamer/impl/reader",
        "//streamer/impl/config",
        "//utils/fd",
        "//utils/env",
    ],
)
