load("//:rules.bzl", "runai_cc_auto_library")

runai_cc_auto_library(
    name = "task",
    deps = [
        "//streamer/impl/request",
        "//utils/logging",
        "//common/backend_api/object_storage",
    ],
)
